/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from depend_Release_CSR101x_A05/app_gatt_db.db_
 */

#include "depend_Release_CSR101x_A05/app_gatt_db.h"

/* GATT database */
uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0003: Characteristic Declaration 2a00 */
    0x3005, 0x0a04, 0x0000, 0x2a00,
    /* 0004: . */
    0xd501, 0x0000,
    /* 0005: Characteristic Declaration 2a01 */
    0x3005, 0x0206, 0x0001, 0x2a00,
    /* 0006: .. */
    0xd002, 0x0000,
    /* 0007: Characteristic Declaration 2a04 */
    0x3005, 0x0208, 0x0004, 0x2a00,
    /* 0008: H`..X. */
    0xd006, 0x4860, 0x0000, 0x5802,
    /* 0009: Primary Service fef1 */
    0x0002, 0xf1fe,
    /* 000a: Characteristic Declaration c4edc000-9daf-11e3-8000-00025b000b00 */
    0x3013, 0x080b, 0x0000, 0x0b00, 0x5b02, 0x0000, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 000b: . */
    0xc501, 0x0000,
    /* 000c: Characteristic Declaration c4edc000-9daf-11e3-8001-00025b000b00 */
    0x3013, 0x020d, 0x0000, 0x0b00, 0x5b02, 0x0001, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 000d: ................ */
    0xc010, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 000e: Characteristic Declaration c4edc000-9daf-11e3-8002-00025b000b00 */
    0x3013, 0x0a0f, 0x0000, 0x0b00, 0x5b02, 0x0002, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 000f: . */
    0xc401, 0x0000,
    /* 0010: Characteristic Declaration c4edc000-9daf-11e3-8003-00025b000b00 */
    0x3013, 0x1c11, 0x0000, 0x0b00, 0x5b02, 0x0003, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0011: . */
    0xc401, 0x0000,
    /* 0012: Client Characteristic Configuration */
    0x6400,
    /* 0013: Characteristic Declaration c4edc000-9daf-11e3-8004-00025b000b00 */
    0x3013, 0x1c14, 0x0000, 0x0b00, 0x5b02, 0x0004, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0014: . */
    0xc401, 0x0000,
    /* 0015: Client Characteristic Configuration */
    0x6400,
    /* 0016: Characteristic Declaration c4edc000-9daf-11e3-8005-00025b000b00 */
    0x3013, 0x0a17, 0x0000, 0x0b00, 0x5b02, 0x0005, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0017: . */
    0xc401, 0x0000,
    /* 0018: Characteristic Declaration c4edc000-9daf-11e3-8006-00025b000b00 */
    0x3013, 0x0a19, 0x0000, 0x0b00, 0x5b02, 0x0006, 0x80e3, 0x11af, 0x9d00, 0xc0ed, 0xc400,
    /* 0019: . */
    0xc401, 0x0000,
};

uint16 *GattGetDatabase(uint16 *len)
{
    *len = sizeof(gattDatabase);
    return gattDatabase;
}

/* End-of-File */
